version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=basa
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: go_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:12345@db:5432/basa?sslmode=disable
    command: ["/main"]

  elasticsearch:
    image: localhost:5000/elasticsearch:7.9.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node

  logstash:
      image: localhost:5000/logstash:7.9.3
      ports:
        - "5044:5044"

  kibana:
      image: localhost:5000/kibana:7.9.3
      ports:
        - "5601:5601"

volumes:
  db_data: